### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by wilsq36** [teamdfir/sift#395]

**Comment by ekristen** [comment]
As you deleted the original description ... for everyone else here it is.

```
Your install instructions suck.
```

You are off to a bad start if you are truly looking for help. This is *NOT* how you ask for help. 

If you care of elaborate on what part of the instructions are not useful, I'll entertain further commentary, otherwise this issue will be closed and locked and further commentary from you will be blocked.

**Comment by wilsq36** [comment]
Sorry, that was meant for another site. I was going back and forth between VMs. My apologies

**Comment by ekristen** [comment]
Stuff happens I’ll just delete thisb
