### ISSUE TITLE
Increase Swap size and move to a partition

### ISSUE THREAD

**Issue by philhagen** [teamdfir/sift#418]
Swap should be larger - 10-20GB and moved to a partition instead of a file on `/`.

Based on OVA of 18.04 VM.

**Comment by ekristen** [comment]
@philhagen unfortunately I'm not sure we can do this. I've looked at it a few different ways and the problem is that we have to "create" the swap file of 10-20GB and that's problematic when creating the OVA for distribution. It might have to be something that's done as a first step in the class work? 

If you have thoughts of how this can be achieved without creating the file ahead of time I'm all hears.

**Comment by ekristen** [comment]
We've enabled swap in the latest builds of the OVA, see https://github.com/teamdfir/sift-packer/blob/master/builtin_files/ubuntu-desktop-preseed.cfg#L250-L252
