### ISSUE TITLE
16.04 SIFT is Broken -- Plaso repo no longer exists for 16.04

### ISSUE THREAD

**Issue by ekristen** [teamdfir/sift#433]
This is a catch all issue for the plaso repo for 16.04 being taken down. 

No fix is in place yet. Check back for updates.

**Comment by WriteCodeEveryday** [comment]
Would it be possible to modify the [following install instructions ](https://digital-forensics.sans.org/community/downloads)?

Under "Option 2: SIFT Easy Installation:", there are directions "Download Ubuntu 16.04 ISO file and install Ubuntu 16.04 on any system" that imply Ubuntu 16.04 should be downloaded instead of Ubuntu 18.04

**Comment by siftuser** [comment]
whats the suggestion for solution ? upgrading ubuntu to 18 would resolve ?

**Comment by siftuser** [comment]
Sorry to bother. But whats the suggested workaround ? upgrading ubuntu would help ? Thanks

**Comment by ekristen** [comment]
Use 18.04 for live without plaso at the moment, as that's the one thing that's missing/broke with 16.04.

**Comment by siftuser** [comment]
> Use 18.04 for live without plaso at the moment, as that's the one thing that's missing/broke with 16.04.

@ekristen  Thanks! works now

**Comment by joachimmetz** [comment]
Ubuntu 16.04 is end of life https://wiki.ubuntu.com/Releases

So we stopped support it, if you really need to run Plaso on an Ubuntu 16.04 installation use Docker instead. I would strongly recommend SIFT to keep their builds up to date instead.
