### ISSUE TITLE
sudo sift update fails

### ISSUE THREAD

**Issue by Stoesi** [teamdfir/sift#467]
I am using the ova version of the Sift Workstation and updated it already several times.
When I run "sudo sift update" now I receive these errors:
Command failed: apt-get update
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
E: Failed to fetch 'https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages 404 Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
I assume it is caused by the move of the Docker repositories from apt.dockerproject.org to download.docker.com
-> https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages
My knowledge about Saltstack is not good enough to solve this.
Where can I find an easy and applicable howto?
Or is it something that can be changed centrally?

**Comment by digitalsleuth** [comment]
@Stoesi Are you using the latest version of the cli? Pretty sure I have an idea what's causing your issue, but to be on the safe side can you include your saltstack.log? It's located at /var/cache/sift/cli/<version_number>/saltstack.log

**Comment by Stoesi** [comment]
@digitalsleuth As mentioned I use the OVA as I have only base knowledge about Linux - and even less (better zero) about SaltStack. The installation run for a few months with some special handling at the beginning, but on my last try to update, I received the above errors.  
In the meantime, I learnt more about SaltStack and was able to make it run again by this procedure:
import the OVA, start and reboot (easiest way for me to get around the error "Could not get lock /var/lib/dpkg/lock - open (11 Resource temporarily unavailable)"
sudo apt-get remove salt-minion salt-common 
sudo apt-get update
sudo apt-get install salt-minion salt-common
sudo sift update
In case you receive still errors, you should repeat this sequence (reason is that salt-common and salt-minion is still not installed - can be verified by sudo apt list salt* ) 
sudo apt-get install salt-minion salt-common
sudo sift update
It is not the smartest way and I cannot explain why sometimes I have to run the reinstall of salt-minion and salt-common twice, but at least it works.
If you still want to see the saltstack.log, just let me know - anyway, thanks for your efforts.

**Comment by digitalsleuth** [comment]
@Stoesi The reason you're seeing the '/var/lib/dpkg/lock' issue is because Ubuntu is attempting to do its auto updates at the same time you may be trying to do an apt update or upgrade. Thus, dpkg has a lock on the file to ensure that your apt update and the systems installation of packages do not conflict. When you have this lock, you can wait a few minutes for the system to complete its search for/installation of updates, and change the /etc/apt/apt.conf.d/20auto-upgrades config to read "0" vice the "1" that it's likely set it. Even without changing this, what you're seeing is normal Ubuntu behavior.

You should not need to re-install salt-minion or salt-common, only complete the apt update && apt upgrade to get the latest version of salt (if it's already installed). And then finally, you'll want to check out the sift-cli releases page to make sure you have the latest release of the cli, then do a sudo sift update and sudo sift upgrade (as necessary).

The reason for the salt re-installation working is because the newer releases of SIFT have some changes in them which are not supported in the older version of salt. What you're essentially doing is removing the old version of salt and installing the new version of salt, which is a roundabout way of just doing an upgrade.

In the end, were you finally able to install SIFT, or did you get errors from the actual `sudo sift update` command? If you received errors, then yes, please attach your saltstack.log. If not, and the installation completed fine, then the issues you mentioned should be resolved by the recommendations about. 

Please try these and let me know how they work out for you.

**Comment by ekristen** [comment]
Support for xenial is being dropped by a lot of tooling. SIFT supports 18.04 (bionic) and  we are currently working on 20.04 support for ubuntu right now.
