### ISSUE TITLE
Installing SIFT using CLI tool 18.04.5 fails

### ISSUE THREAD

**Issue by jdecrosta** [teamdfir/sift#487]
Hello,

   New to GitHub and am trying to install SIFT for a forensics class I am in. I have followed the instructions provided by my school and other Github threads regarding issues similar to mine but am a bit stuck. I am running "sudo sift install" after downloading the appropriate files from the SIFT webpage and the install fails with "Error: update returned exit code not zero". I have attached the saltstack.log to this post and would be appreciative of any help you all could provide.

- Jared 

![Installing Sift issue](https://user-images.githubusercontent.com/70543700/91764176-d80b3b00-eba4-11ea-87ce-9328bd629079.PNG)
[saltstack.log](https://github.com/teamdfir/sift/files/5152447/saltstack.log)

**Comment by ekristen** [comment]
Looks like only a few things failed like timesketch from the logs which is sorta a known issue at the moment.

**Comment by jdecrosta** [comment]
@ekristen thank you for the quick reply. Based on what you have seen, is SIFT installed in my Ubuntu instance or is there something more I need to be doing?

**Comment by jdecrosta** [comment]
I ask the above question because I checked the version installed and it shows that there is none - see attached photo.
![Sift not installed](https://user-images.githubusercontent.com/70543700/91773464-d5184680-ebb4-11ea-8a47-9856783672af.PNG)

**Comment by ekristen** [comment]
Yeah so it's a bit misleading unfortunately. If it can't complete 100% it doesn't mark that it was installed, it's a flaw, but basically everything is 100% separate from each other so all the bits that did install, remain, just the ones that failed do not.

**Comment by ekristen** [comment]
Try this https://github.com/teamdfir/sift-cli/releases/tag/v1.9.0-rc4

**Comment by ED-209-MK7** [comment]
This is really disappointing. I have never seen SIFT so broken. Through a lot of trouble shooting and frankly guessing, most of my students and I got around this. Some were able to get past the .js issue about by trying the pre-release... others it worked fine out of the box.

When you run `sift update` it seems to look for and has a salt file in the /tmp dir that isn't there.... it says it is expecting '' (blank)... but finding a hash for a file that doesn't exist. When you run upgrade it give the js error.

Please fix and or re-release the VM. SIFT has never been like this....

**Comment by ekristen** [comment]
Hi @ED-209-MK7 I'm assuming you are stating you are seeing the same error above? 

If you'd like better assistance in the future, providing more details would of more benefit.

> it seems to look for and has a salt file in the /tmp dir that isn't there

The CLI tool uses the internet to make a connection to GitHub where the source files for the Open Source Community Edition of SIFT resides. It downloads those files to the `/tmp` directory and performs a hashing function against to VALIDATE the integrity of the download.

> it says it is expecting '' (blank)... but finding a hash for a file that doesn't exist.

This would indicate that it is unable to download the file successful, likely due to local networking problems, but if you can provide more output, I'd be happy to investigate a problem with the tool itself.

In general, please install the latest CLI tool https://github.com/teamdfir/sift-cli/releases/tag/v1.9.1 -- or if you'd rather install or upgrade manually please see the manual installation instructions at https://github.com/teamdfir/sift-saltstack.

**Comment by ekristen** [comment]
@jdecrosta were you ever able to download the latest CLI and try again, a few adjustments have been made thanks to feedback and testing by other members of the community.

**Comment by ED-209-MK7** [comment]
I got it... for the newly downloaded VM.

Import the OVA.
Once logged in open a CLI...
```
sudo curl -Lo /usr/local/bin/sift https://github.com/teamdfir/sift-cli/releases/download/v1.9.0-rc4/sift-cli-linux
sudo chmod +x /usr/local/bin/sift
sudo apt-mark unhold salt*
sudo sift upgrade
```

It seems the first issue is that the VM was pushed out without a SIFT CLI being installed. Once the new SIFT CLI is installed it is looking to upgrade the salt-minion but is having issues because the VM ships with those packages being held.

A humble recommendation is that SIFT CLI check for this situation, unhold the packages, and then carry on...

**Comment by ekristen** [comment]
> It seems the first issue is that the VM was pushed out without a SIFT CLI being installed.

This was an oversight, as we use to install it as part of the install process but that led to odd behavior so it was removed. Since we do not use the CLI to build the VM it wasn't getting installed. I can take note to add it back.

> Once the new SIFT CLI is installed it is looking to upgrade the salt-minion but is having issues because the VM ships with those packages being held.

The CLI tool allows for change to held packages https://github.com/teamdfir/sift-cli/blob/master/sift-cli.js#L238 

Can you provide any output that suggests it is unable to upgrade due to held packages? It's possible that CLI option isn't being honored, but we haven't had a problem in the past.

**Comment by ED-209-MK7** [comment]
![image](https://user-images.githubusercontent.com/29338568/93924732-5c4b6c80-fcd2-11ea-82e6-7583064a5df3.png)


I saw that, and checked for a hold. There was hold out of the box...

![image](https://user-images.githubusercontent.com/29338568/93924861-8e5cce80-fcd2-11ea-9139-0240d8e99aff.png)

Then tried it again....

![image](https://user-images.githubusercontent.com/29338568/93925019-bcdaa980-fcd2-11ea-88dd-328f26f04615.png)





And hey oversights happen. I would be lying if I said I haven't done it plenty as an Engineer! I hope this helps out.

**Comment by ekristen** [comment]
https://github.com/teamdfir/sift-cli/releases/tag/v1.9.2 -- fixes the held package on package remove issue in the first screenshot.

**Comment by ED-209-MK7** [comment]
HOLY SMOKES!!! Did you literally just go fix that and push it?!? Impressive!

Thanks!

**Comment by ekristen** [comment]
Yes I did. You gave me enough info to see where the problem was in the last post, thanks, it's an edge case I wasn't setup to test.

**Comment by ED-209-MK7** [comment]
My disappointment is now ... envy! Thanks @ekristen !

**Comment by jdecrosta** [comment]
> @jdecrosta were you ever able to download the latest CLI and try again, a few adjustments have been made thanks to feedback and testing by other members of the community.

Erik,

   Apologies for the delay in replying - yes, I was able use this to fix the errors. Thanks so much for your quick reply!

**Comment by ekristen** [comment]
Great.
