### ISSUE TITLE
Docker SIFT / pip conflict

### ISSUE THREAD

**Issue by michealb40** [teamdfir/sift#513]
I am attempting to create a docker image for SIFT using 2021.4 / Ubuntu 20.04.  It seems they moved the pip 21 URL.  I cannot seem to bypass this issue.  Logs attached.  I attempted to install pip 21 manually but I am not sure if it is still causing a conflict. Any advise is appreciated. 

[results.yml.gz](https://github.com/teamdfir/sift/files/6223886/results.yml.gz)
[saltstack.log.gz](https://github.com/teamdfir/sift/files/6223887/saltstack.log.gz)
[minion.gz](https://github.com/teamdfir/sift/files/6223888/minion.gz)

**Comment by digitalsleuth** [comment]
Hi @michealb40, I have submitted a pull request to correct the python2 PIP issue, however if you install python2 first, then `curl -o /tmp/get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py ` then `python2 /tmp/get-pip.py` you should be able to continue with the install normally.

I have a docker building as we speak with this configuration to test based on focal. Once it's confirmed working, I'll share the Dockerfile details.

**Comment by michealb40** [comment]
That did it!! Thanks a bunch for that!  I have a fully functional docker for testing.  I very much appreciate your help on that one.  

I am going to push this one up overnight. Please feel free to use it for your testing/confirmation as well.

>> dfwforensics/sift2021_4_0ubuntu_20_04

sha256:ad75713c9d44fc565adbed3a608f6c48f02a6405753b8a16c54f566107be4c4f

**Comment by digitalsleuth** [comment]
Hi @michealb40 Glad to hear it's resolved. If you need some SIFT docker images, I have a couple available on the docker hub (just updated them with the newest releases for both bionic and focal). You can also find a docker-compose with the Dockerfiles at https://github.com/digitalsleuth/sift-docker for ease of configuration as well.

Erik has already merged the fix for the python2 pip issue, so you should also be able to update your Dockerfile to remove the need for get-pip.

Cheers!

**Comment by michealb40** [comment]
Absolutely helpful and very appreciated!  Please let me know if there is
anything I can do to help.
