### ISSUE TITLE
Feature request - SIFT to Ubuntu 21.04 (Hirsute Hippo)

### ISSUE THREAD

**Issue by rbnmaia** [teamdfir/sift#541]
Requesting if you can validate 21.04 to support SIFT update and upgrade as usable distro.
If there will be a plan workaround to re-use the 20.04 server and desktop variant by manipulating files, please also let me know.

**Comment by digitalsleuth** [comment]
Since a successful install of SIFT on anything above 20.04 will require a number of repos to support 21.04 (GIFT, SIFT, SaltStack), this will likely take some time before it can be supported. Especially from a SaltStack standpoint, which still only supports 20.04. With 22.04 coming around the corner (newest LTS), that might be a better option for support.

**Comment by ekristen** [comment]
@digitalsleuth points out several good points, while I could open support for the newer version, the apt repos would definitely be a problem.

**Comment by ekristen** [comment]
@rbnmaia we unfortunately have to wait until several of our dependencies support to officially support, but in the new version of the CLI I'm working on, I'll make sure to add provisions to allow you to override the restriction even though things will fail.
