### ISSUE TITLE
Update / Upgrade as of Spring 2021 OVA

### ISSUE THREAD

**Issue by itpropaul** [teamdfir/sift#545]
I don't see the "sift" command available in the OVA.

Beyond apt update and apt upgrade, is there a sift-specific way that I should be updating the VM and it's included tools?

**Comment by ekristen** [comment]
Yes, the latest build script didn't include it, you can easily download it from https://github.com/teamdfir/sift-cli and then run the install, it won't think it's installed only because a single file doesn't exist, but the SIFT scripts are all idempotent and so it'll run through and see what's different, what's the same and make any necessary changes..

**Comment by itpropaul** [comment]
Okay, thanks! Do you recommend solely using sift to update/upgrade the VM or still use apt? 

I'm wondering if using apt would break dependencies, etc.

**Comment by ekristen** [comment]
The SIFT CLI will do things apt doesn’t, apt is going to cover probably 70% or so.

**Comment by itpropaul** [comment]
Awesome, thanks @ekristen!
