### ISSUE TITLE
ARM Support for SIFT-CLI

### ISSUE THREAD

**Issue by n3tl0kr** [teamdfir/sift#573]
Like many others, I had to set my MBP to pasture and ended up with an M1 Max.  While the M1 runs Ubuntu ARM with no issues, we can't import the prebuilt SIFT OVA and the SIFT CLI is an x64 ELF binary presently. Not sure if it's just a matter of cross compiling but I thought I'd ask for goodness sake :)

**Comment by ekristen** [comment]
Hi @n3tl0kr thanks for the issue. There likely won't be any more work done with the `sift-cli` specifically, it's successor a new project I've been working on https://github.com/ekristen/cast/

I've actually just pushed [0.10.0](https://github.com/ekristen/cast/releases/tag/v0.10.0) that adds support for `linux/arm64`

Unfortunately I already know it won't work 100%, we've been doing some testing and know there are many linux packages that do not have arm64 variants at this time. Last time I did testing only about 70% of things were installed/configured properly but it has been a few months since that full test.

More recently we've been working on 22.04 support.

I would love to get feedback on cast from you if you are interested.

**Comment by ekristen** [comment]
You can attempt this with the latest version of cast along with the `--pre-release` flag on Ubuntu 20.04, unfortunately 22.04 is not yet supported.

**Comment by ekristen** [comment]
There's been minimal success with ARM64, there are LOT of packages unfortunately that are not compiled for it. 

22.04 support is likely to land by Feb 15th. March 1st, 2023 the sift-cli will officially be replaced with [cast](https://github.com/ekristen/cast)

**Comment by ekristen** [comment]
Tracking overall ARM support in #592
