### ISSUE TITLE
Saltstack issue

### ISSUE THREAD

**Issue by mskarsem** [teamdfir/sift#576]
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: desktop
Installing and configuring SaltStack properly ...

Command failed: wget -O - https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/salt-archive-keyring.gpg | apt-key add -
--2022-09-20 20:41:55--  https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/salt-archive-keyring.gpg
Resolving repo.saltproject.io (repo.saltproject.io)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘repo.saltproject.io’
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

Error: Command failed: wget -O - https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/salt-archive-keyring.gpg | apt-key add -
--2022-09-20 20:41:55--  https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/salt-archive-keyring.gpg
Resolving repo.saltproject.io (repo.saltproject.io)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘repo.saltproject.io’
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove

**Comment by mskarsem** [comment]
Keep getting this when I try to install sift on desktop. any one got a solution for this?

**Comment by mskarsem** [comment]
Tried to fix it with 
sudo curl -fsSL -o /usr/share/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/salt-archive-keyring.gpg

But now i get another fault ofcourse. 

E: Conflicting values set for option Signed-By regarding source https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004/ focal: /usr/share/keyrings/salt-archive-keyring.gpg != 
E: The list of sources could not be read.

**Comment by digitalsleuth** [comment]
Hi there @mskarsem , the first issue you had was due to a network connectivity / DNS resolution error, and wasn't as a result of the installation process: `Resolving repo.saltproject.io (repo.saltproject.io)... failed: Temporary failure in name resolution.`

The second error you're receiving is due to the changes you made after this. Your best bet would be to delete the `/usr/share/keyrings/salt-archive-keyring.gpg` file, then delete the `/etc/apt/sources.list.d/saltstack.list` and possible `/etc/apt/sources.list.d/salt.list` files. Once deleted, run `sudo apt update`, then attempt the SIFT install again.
