### ISSUE TITLE
Hashes do not match after "sudo sift install"

### ISSUE THREAD

**Issue by paulthesoccer** [teamdfir/sift#600]
Hello,

at first, thanks for the sift-project. 
when i try to install sift workstation, it fails with error-message.

The error - message is as follows:
Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz

console output full version:

sudo sift install
[sudo] password for axiom:
Sorry, try again.
[sudo] password for axiom:
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: desktop
> downloading v2023.02.06
>> downloading sift-saltstack-v2023.02.06.tar.gz.asc
>> downloading sift-saltstack-v2023.02.06.tar.gz.sha256
>> downloading sift-saltstack-v2023.02.06.tar.gz.sha256.asc
>> downloading sift-saltstack-v2023.02.06.tar.gz
> validating file sift-saltstack-v2023.02.06.tar.gz

Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz

Error: Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz

    at validateFile (/snapshot/sift-cli/sift-cli.js:411:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:478:3)
    at async run (/snapshot/sift-cli/sift-cli.js:772:5)
    at async main (/snapshot/sift-cli/sift-cli.js:795:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'
***************************

it is a brand new wls ubuntu::

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

on a brand new windows 10:
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

both os'es fully updated.

i have no idea, how to fix that.

**Comment by ekristen** [comment]
Use https://github.com/ekristen/cast to install.Sent from my iPhoneOn Jun 21, 2023, at 00:52, paulthesoccer ***@***.***> wrote:﻿
Hello,
at first, thanks for the sift-project.
when i try to install sift workstation, it fails with error-message.
The error - message is as follows:
Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz
console output full version:
sudo sift install
[sudo] password for axiom:
Sorry, try again.
[sudo] password for axiom:

***@***.***+0-g0582d2b
sift-version: notinstalled


mode: desktop
downloading v2023.02.06

downloading sift-saltstack-v2023.02.06.tar.gz.asc
downloading sift-saltstack-v2023.02.06.tar.gz.sha256
downloading sift-saltstack-v2023.02.06.tar.gz.sha256.asc
downloading sift-saltstack-v2023.02.06.tar.gz
validating file sift-saltstack-v2023.02.06.tar.gz


Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz
Error: Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz
at validateFile (/snapshot/sift-cli/sift-cli.js:411:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:478:3)
at async run (/snapshot/sift-cli/sift-cli.js:772:5)
at async main (/snapshot/sift-cli/sift-cli.js:795:5)

----- PLEASE READ ----------------------
A lot of failures are caused by the apt system being locked
or unhealthy.
Before opening an issue in GitHub, please check to see if
your apt system is healthy.
Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'

it is a brand new wls ubuntu::
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
on a brand new windows 10:
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
both os'es fully updated.
i have no idea, how to fix that.

**Comment by ekristen** [comment]
Please use [cast](https://github.com/ekristen/cast) to install sift. `sudo cast install sift` -- it is the successor to the sift-cli.
