### ISSUE TITLE
SIFT does not like my school's website

### ISSUE THREAD

**Issue by monVMissues** [teamdfir/sift#614]
Per an assignment I am doing I need to move files from one VM into another (Windows VM into SIFT VM). To do this I have tried to load my school's website/OneDrive but neither google or firefox let me in.

**Comment by philhagen** [comment]
I'm not sure that is a SIFT issue, but maybe a network access restriction?  Can you provide some more detail about what kind of error you're receiving?

**Comment by monVMissues** [comment]
The page itself for my school's website won't load, but I can get Google to load (I have already shut down my VM for the day and it takes a long time to load so hopefully that's helpful for now)

**Comment by philhagen** [comment]
thanks.  this definitely sounds like something in your local environment is causing the problem.  I am quite confident it's not related to the VM.  you might need to work with your school's IT department or Helpdesk to determine what the problem is.  I don't think we'd be able to provide much help, unfortunately.
